name: bashtest

on: [push]

jobs:
  bashtest:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, 'no-workflow')"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Install GDAL
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin python3-gdal
      - name: Run bash tests
        env:
          FIRMS_MAP_KEY: ${{ secrets.FIRMS_MAP_KEY }}
          COPERNICUS_AWS_ACCESS_KEY_ID: ${{ secrets.COPERNICUS_AWS_ACCESS_KEY_ID }}
          COPERNICUS_AWS_SECRET_ACCESS_KEY: ${{ secrets.COPERNICUS_AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "FIRMS_MAP_KEY: $FIRMS_MAP_KEY"
          echo "COPERNICUS_AWS_ACCESS_KEY_ID: $COPERNICUS_AWS_ACCESS_KEY_ID"
          echo "COPERNICUS_AWS_SECRET_ACCESS_KEY: $COPERNICUS_AWS_SECRET_ACCESS_KEY"

          ./.github/workflows/bashtest.sh bluer_geo
